### ISSUE TITLE
No matching distribution found for plams>=1.2

### ISSUE THREAD

**Issue by BvB93** [SCM-NV/qmflows#102]
Could not find a version that satisfies the requirement plams>=1.2 (from qmflows==0.3.0) (from versions: 1.1.1)
No matching distribution found for plams>=1.2 (from qmflows==0.3.0)

This issue seems to occur when installing qmflows (master or scripts branch) and i haven't been able to figure out how to fix it.

**Comment by felipeZ** [comment]
Currently we are making use of functionality available only in **plams==0.1.2** but there is not such release in [pypi](https://pypi.org/project/PLAMS/), that version is only available in the master branch of Plams in github. 
There is a line in the [setup.py](https://github.com/SCM-NV/qmflows/blob/scripts/setup.py) that points to the location of plams.
```
    dependency_links=[
        "https://github.com/SCM-NV/plams/tarball/master#egg=plams"]
```
But as far I understand pip ignores it. It only looks for that version in PyPI, therefore the only solution are:
 * Install by hand like: ```pip install git+https://github.com/SCM-NV/PLAMS@master#egg=plams-1.2```
 * Release plams 1.2

Since I have not control Plams the first option is the only available

**Comment by h4nsu** [comment]
Hi guys,
Sorry for the problem, that's my fault :/
Plams 1.3 is going to be released very soon and it's going to be more or less the version from AMS2018 plus some additional documentation.
Meanwhile, if it makes your life easier, I can attach 1.2 release tag to an arbitrary point in history (and put it on PyPi if needed). Just point me to a commit you want to become v1.2.

**Comment by felipeZ** [comment]
@h4nsu We are currently working with the master version from github, therefore if you attach the 1.2 release on PyPi to the current master state that will be great. Thanks for the fix!

**Comment by h4nsu** [comment]
I'm planning to do the 1.3 release within next two weeks and I thought it would look a bit strange to have 1.2 and 1.3 versions differing by just a few commits. Could you wait a few days or is it urgent?

**Comment by felipeZ** [comment]
It is not really urgent, when you release the new PLAMS we can change the dependencies in qmflows.

**Comment by BvB93** [comment]
Recently i added three functions to rdkit.py for finding the global minimum (or at least attempt to). It would be great these additions could be included in the 1.3 release as well.

**Comment by h4nsu** [comment]
@BvB93 Yes, that's the plan :) I saw your merge request, I'll take care of it in the next few days.

**Comment by BvB93** [comment]
Issue no longer relevant.
